version: "3.8"

services:
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/myDb
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
